# Generated by Django 3.1.5 on 2021-01-21 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('priorities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.category', verbose_name='todo_category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='priorities.priority', verbose_name='todo_priority'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='todo_user'),
        ),
    ]
