# Generated by Django 3.1.5 on 2021-01-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20210127_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='completed',
        ),
    ]
